import "@stencil/redux";
import 'manifesto.js';
import { Store, Unsubscribe } from "@stencil/redux";
import { setDocumentUrl, setDocumentContentType, setStatus, addOverlay, setOptions, setLocale, addLocale } from '../../store/actions/document';
export declare class ViewerComponent {
    el: HTMLElement;
    language: string;
    navigationEnable: boolean;
    navigationHeight?: number;
    navigationLocation: PlacementType;
    annotationsEnable: boolean;
    backgroundColor: string;
    documentUrl: string;
    addLocale: typeof addLocale;
    addOverlayState: typeof addOverlay;
    setDocumentContentType: typeof setDocumentContentType;
    setDocumentUrl: typeof setDocumentUrl;
    setLocale: typeof setLocale;
    setStatus: typeof setStatus;
    setOptions: typeof setOptions;
    storeUnsubscribe: Unsubscribe;
    locale: MyAppState["document"]["locale"];
    page: MyAppState["document"]["page"];
    url: MyAppState["document"]["url"];
    status: MyAppState["document"]["status"];
    viewport: MyAppState["document"]["viewport"];
    store: Store;
    private i18n;
    getPage(): Promise<number>;
    addOverlay(x: number, y: number, width: number, height: number, text: string): Promise<void>;
    handleUrlChange(): void;
    handleDocumentClick(): void;
    handleLanguageChange(): void;
    componentWillLoad(): void;
    componentDidLoad(): void;
    componentDidUnload(): void;
    configure(): void;
    render(): any;
}
