/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MessageType,
} from './components/message/message-options';

export namespace Components {
  interface HarmonizedButton {
    'disabled': boolean;
    'fontSize': number;
    'fullWidth': boolean;
    'icon': string;
    'label': string;
    'outline': boolean;
    'raised': boolean;
    'size': string;
    'tooltip': string;
  }
  interface HarmonizedContent {
    'placement': PlacementType;
    'rows': number;
    'showMetadata': boolean;
    'showNavigation': boolean;
    'visible': boolean;
    'width': number;
  }
  interface HarmonizedDrawer {
    'close': () => Promise<void>;
    'open': () => Promise<void>;
    'placement': PlacementType;
    'toolbar': boolean;
    'visible': boolean;
  }
  interface HarmonizedImage {
    'caption': string;
    'page': number;
    'preload': boolean;
    'showCaption': boolean;
    'showTooltip': boolean;
    'src': string;
    'srcset': string;
  }
  interface HarmonizedImageList {}
  interface HarmonizedMessage {
    'text': string;
    'type': MessageType;
  }
  interface HarmonizedNavigation {
    'cols': number;
    'placement': PlacementType;
    'rows': number;
    'theme': string;
  }
  interface HarmonizedOpenseadragon {
    'getOverlays': () => Promise<DocumentOverlay[]>;
    'openseadragon': () => Promise<any>;
  }
  interface HarmonizedOverlay {
    'height': number;
    'mouseTracker': any;
    'width': number;
    'x': number;
    'y': number;
  }
  interface HarmonizedPager {}
  interface HarmonizedPdf {}
  interface HarmonizedSpinner {}
  interface HarmonizedTab {
    'active': boolean;
    'icon': string;
    'label': string;
  }
  interface HarmonizedTabs {}
  interface HarmonizedTopbar {
    'backgroundColor': string;
  }
  interface HarmonizedViewer {
    'addOverlay': (x: number, y: number, width: number, height: number) => Promise<void>;
    'backgroundColor': string;
    'documentUrl': string;
    'exitFullscreen': () => Promise<void>;
    'fullscreen': () => Promise<void>;
    'getPage': () => Promise<number>;
    'navigationEnable': boolean;
    'navigationPlacement': PlacementType;
    'pagingEnable': boolean;
  }
  interface HarmonizedViewport {
    'annotationsEnable': boolean;
  }
  interface HarmonizedZoomSlider {}
  interface HvAnnotations {}
  interface HvStatusbar {}
}

declare global {


  interface HTMLHarmonizedButtonElement extends Components.HarmonizedButton, HTMLStencilElement {}
  var HTMLHarmonizedButtonElement: {
    prototype: HTMLHarmonizedButtonElement;
    new (): HTMLHarmonizedButtonElement;
  };

  interface HTMLHarmonizedContentElement extends Components.HarmonizedContent, HTMLStencilElement {}
  var HTMLHarmonizedContentElement: {
    prototype: HTMLHarmonizedContentElement;
    new (): HTMLHarmonizedContentElement;
  };

  interface HTMLHarmonizedDrawerElement extends Components.HarmonizedDrawer, HTMLStencilElement {}
  var HTMLHarmonizedDrawerElement: {
    prototype: HTMLHarmonizedDrawerElement;
    new (): HTMLHarmonizedDrawerElement;
  };

  interface HTMLHarmonizedImageElement extends Components.HarmonizedImage, HTMLStencilElement {}
  var HTMLHarmonizedImageElement: {
    prototype: HTMLHarmonizedImageElement;
    new (): HTMLHarmonizedImageElement;
  };

  interface HTMLHarmonizedImageListElement extends Components.HarmonizedImageList, HTMLStencilElement {}
  var HTMLHarmonizedImageListElement: {
    prototype: HTMLHarmonizedImageListElement;
    new (): HTMLHarmonizedImageListElement;
  };

  interface HTMLHarmonizedMessageElement extends Components.HarmonizedMessage, HTMLStencilElement {}
  var HTMLHarmonizedMessageElement: {
    prototype: HTMLHarmonizedMessageElement;
    new (): HTMLHarmonizedMessageElement;
  };

  interface HTMLHarmonizedNavigationElement extends Components.HarmonizedNavigation, HTMLStencilElement {}
  var HTMLHarmonizedNavigationElement: {
    prototype: HTMLHarmonizedNavigationElement;
    new (): HTMLHarmonizedNavigationElement;
  };

  interface HTMLHarmonizedOpenseadragonElement extends Components.HarmonizedOpenseadragon, HTMLStencilElement {}
  var HTMLHarmonizedOpenseadragonElement: {
    prototype: HTMLHarmonizedOpenseadragonElement;
    new (): HTMLHarmonizedOpenseadragonElement;
  };

  interface HTMLHarmonizedOverlayElement extends Components.HarmonizedOverlay, HTMLStencilElement {}
  var HTMLHarmonizedOverlayElement: {
    prototype: HTMLHarmonizedOverlayElement;
    new (): HTMLHarmonizedOverlayElement;
  };

  interface HTMLHarmonizedPagerElement extends Components.HarmonizedPager, HTMLStencilElement {}
  var HTMLHarmonizedPagerElement: {
    prototype: HTMLHarmonizedPagerElement;
    new (): HTMLHarmonizedPagerElement;
  };

  interface HTMLHarmonizedPdfElement extends Components.HarmonizedPdf, HTMLStencilElement {}
  var HTMLHarmonizedPdfElement: {
    prototype: HTMLHarmonizedPdfElement;
    new (): HTMLHarmonizedPdfElement;
  };

  interface HTMLHarmonizedSpinnerElement extends Components.HarmonizedSpinner, HTMLStencilElement {}
  var HTMLHarmonizedSpinnerElement: {
    prototype: HTMLHarmonizedSpinnerElement;
    new (): HTMLHarmonizedSpinnerElement;
  };

  interface HTMLHarmonizedTabElement extends Components.HarmonizedTab, HTMLStencilElement {}
  var HTMLHarmonizedTabElement: {
    prototype: HTMLHarmonizedTabElement;
    new (): HTMLHarmonizedTabElement;
  };

  interface HTMLHarmonizedTabsElement extends Components.HarmonizedTabs, HTMLStencilElement {}
  var HTMLHarmonizedTabsElement: {
    prototype: HTMLHarmonizedTabsElement;
    new (): HTMLHarmonizedTabsElement;
  };

  interface HTMLHarmonizedTopbarElement extends Components.HarmonizedTopbar, HTMLStencilElement {}
  var HTMLHarmonizedTopbarElement: {
    prototype: HTMLHarmonizedTopbarElement;
    new (): HTMLHarmonizedTopbarElement;
  };

  interface HTMLHarmonizedViewerElement extends Components.HarmonizedViewer, HTMLStencilElement {}
  var HTMLHarmonizedViewerElement: {
    prototype: HTMLHarmonizedViewerElement;
    new (): HTMLHarmonizedViewerElement;
  };

  interface HTMLHarmonizedViewportElement extends Components.HarmonizedViewport, HTMLStencilElement {}
  var HTMLHarmonizedViewportElement: {
    prototype: HTMLHarmonizedViewportElement;
    new (): HTMLHarmonizedViewportElement;
  };

  interface HTMLHarmonizedZoomSliderElement extends Components.HarmonizedZoomSlider, HTMLStencilElement {}
  var HTMLHarmonizedZoomSliderElement: {
    prototype: HTMLHarmonizedZoomSliderElement;
    new (): HTMLHarmonizedZoomSliderElement;
  };

  interface HTMLHvAnnotationsElement extends Components.HvAnnotations, HTMLStencilElement {}
  var HTMLHvAnnotationsElement: {
    prototype: HTMLHvAnnotationsElement;
    new (): HTMLHvAnnotationsElement;
  };

  interface HTMLHvStatusbarElement extends Components.HvStatusbar, HTMLStencilElement {}
  var HTMLHvStatusbarElement: {
    prototype: HTMLHvStatusbarElement;
    new (): HTMLHvStatusbarElement;
  };
  interface HTMLElementTagNameMap {
    'harmonized-button': HTMLHarmonizedButtonElement;
    'harmonized-content': HTMLHarmonizedContentElement;
    'harmonized-drawer': HTMLHarmonizedDrawerElement;
    'harmonized-image': HTMLHarmonizedImageElement;
    'harmonized-image-list': HTMLHarmonizedImageListElement;
    'harmonized-message': HTMLHarmonizedMessageElement;
    'harmonized-navigation': HTMLHarmonizedNavigationElement;
    'harmonized-openseadragon': HTMLHarmonizedOpenseadragonElement;
    'harmonized-overlay': HTMLHarmonizedOverlayElement;
    'harmonized-pager': HTMLHarmonizedPagerElement;
    'harmonized-pdf': HTMLHarmonizedPdfElement;
    'harmonized-spinner': HTMLHarmonizedSpinnerElement;
    'harmonized-tab': HTMLHarmonizedTabElement;
    'harmonized-tabs': HTMLHarmonizedTabsElement;
    'harmonized-topbar': HTMLHarmonizedTopbarElement;
    'harmonized-viewer': HTMLHarmonizedViewerElement;
    'harmonized-viewport': HTMLHarmonizedViewportElement;
    'harmonized-zoom-slider': HTMLHarmonizedZoomSliderElement;
    'hv-annotations': HTMLHvAnnotationsElement;
    'hv-statusbar': HTMLHvStatusbarElement;
  }
}

declare namespace LocalJSX {
  interface HarmonizedButton {
    'disabled'?: boolean;
    'fontSize'?: number;
    'fullWidth'?: boolean;
    'icon'?: string;
    'label'?: string;
    'outline'?: boolean;
    'raised'?: boolean;
    'size'?: string;
    'tooltip'?: string;
  }
  interface HarmonizedContent {
    'placement'?: PlacementType;
    'rows'?: number;
    'showMetadata'?: boolean;
    'showNavigation'?: boolean;
    'visible'?: boolean;
    'width'?: number;
  }
  interface HarmonizedDrawer {
    'placement'?: PlacementType;
    'toolbar'?: boolean;
    'visible'?: boolean;
  }
  interface HarmonizedImage {
    'caption'?: string;
    'onImageAdded'?: (event: CustomEvent<any>) => void;
    'onImageLoad'?: (event: CustomEvent<any>) => void;
    'page'?: number;
    'preload'?: boolean;
    'showCaption'?: boolean;
    'showTooltip'?: boolean;
    'src'?: string;
    'srcset'?: string;
  }
  interface HarmonizedImageList {}
  interface HarmonizedMessage {
    'text'?: string;
    'type'?: MessageType;
  }
  interface HarmonizedNavigation {
    'cols'?: number;
    'placement'?: PlacementType;
    'rows'?: number;
    'theme'?: string;
  }
  interface HarmonizedOpenseadragon {
    'onOverlayClick'?: (event: CustomEvent<any>) => void;
    'onPageLoad'?: (event: CustomEvent<any>) => void;
  }
  interface HarmonizedOverlay {
    'height'?: number;
    'mouseTracker'?: any;
    'width'?: number;
    'x'?: number;
    'y'?: number;
  }
  interface HarmonizedPager {}
  interface HarmonizedPdf {}
  interface HarmonizedSpinner {}
  interface HarmonizedTab {
    'active'?: boolean;
    'icon'?: string;
    'label'?: string;
  }
  interface HarmonizedTabs {}
  interface HarmonizedTopbar {
    'backgroundColor'?: string;
  }
  interface HarmonizedViewer {
    'backgroundColor'?: string;
    'documentUrl'?: string;
    'navigationEnable'?: boolean;
    'navigationPlacement'?: PlacementType;
    'onStatusChanged'?: (event: CustomEvent<any>) => void;
    'pagingEnable'?: boolean;
  }
  interface HarmonizedViewport {
    'annotationsEnable'?: boolean;
  }
  interface HarmonizedZoomSlider {}
  interface HvAnnotations {}
  interface HvStatusbar {}

  interface IntrinsicElements {
    'harmonized-button': HarmonizedButton;
    'harmonized-content': HarmonizedContent;
    'harmonized-drawer': HarmonizedDrawer;
    'harmonized-image': HarmonizedImage;
    'harmonized-image-list': HarmonizedImageList;
    'harmonized-message': HarmonizedMessage;
    'harmonized-navigation': HarmonizedNavigation;
    'harmonized-openseadragon': HarmonizedOpenseadragon;
    'harmonized-overlay': HarmonizedOverlay;
    'harmonized-pager': HarmonizedPager;
    'harmonized-pdf': HarmonizedPdf;
    'harmonized-spinner': HarmonizedSpinner;
    'harmonized-tab': HarmonizedTab;
    'harmonized-tabs': HarmonizedTabs;
    'harmonized-topbar': HarmonizedTopbar;
    'harmonized-viewer': HarmonizedViewer;
    'harmonized-viewport': HarmonizedViewport;
    'harmonized-zoom-slider': HarmonizedZoomSlider;
    'hv-annotations': HvAnnotations;
    'hv-statusbar': HvStatusbar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'harmonized-button': LocalJSX.HarmonizedButton & JSXBase.HTMLAttributes<HTMLHarmonizedButtonElement>;
      'harmonized-content': LocalJSX.HarmonizedContent & JSXBase.HTMLAttributes<HTMLHarmonizedContentElement>;
      'harmonized-drawer': LocalJSX.HarmonizedDrawer & JSXBase.HTMLAttributes<HTMLHarmonizedDrawerElement>;
      'harmonized-image': LocalJSX.HarmonizedImage & JSXBase.HTMLAttributes<HTMLHarmonizedImageElement>;
      'harmonized-image-list': LocalJSX.HarmonizedImageList & JSXBase.HTMLAttributes<HTMLHarmonizedImageListElement>;
      'harmonized-message': LocalJSX.HarmonizedMessage & JSXBase.HTMLAttributes<HTMLHarmonizedMessageElement>;
      'harmonized-navigation': LocalJSX.HarmonizedNavigation & JSXBase.HTMLAttributes<HTMLHarmonizedNavigationElement>;
      'harmonized-openseadragon': LocalJSX.HarmonizedOpenseadragon & JSXBase.HTMLAttributes<HTMLHarmonizedOpenseadragonElement>;
      'harmonized-overlay': LocalJSX.HarmonizedOverlay & JSXBase.HTMLAttributes<HTMLHarmonizedOverlayElement>;
      'harmonized-pager': LocalJSX.HarmonizedPager & JSXBase.HTMLAttributes<HTMLHarmonizedPagerElement>;
      'harmonized-pdf': LocalJSX.HarmonizedPdf & JSXBase.HTMLAttributes<HTMLHarmonizedPdfElement>;
      'harmonized-spinner': LocalJSX.HarmonizedSpinner & JSXBase.HTMLAttributes<HTMLHarmonizedSpinnerElement>;
      'harmonized-tab': LocalJSX.HarmonizedTab & JSXBase.HTMLAttributes<HTMLHarmonizedTabElement>;
      'harmonized-tabs': LocalJSX.HarmonizedTabs & JSXBase.HTMLAttributes<HTMLHarmonizedTabsElement>;
      'harmonized-topbar': LocalJSX.HarmonizedTopbar & JSXBase.HTMLAttributes<HTMLHarmonizedTopbarElement>;
      'harmonized-viewer': LocalJSX.HarmonizedViewer & JSXBase.HTMLAttributes<HTMLHarmonizedViewerElement>;
      'harmonized-viewport': LocalJSX.HarmonizedViewport & JSXBase.HTMLAttributes<HTMLHarmonizedViewportElement>;
      'harmonized-zoom-slider': LocalJSX.HarmonizedZoomSlider & JSXBase.HTMLAttributes<HTMLHarmonizedZoomSliderElement>;
      'hv-annotations': LocalJSX.HvAnnotations & JSXBase.HTMLAttributes<HTMLHvAnnotationsElement>;
      'hv-statusbar': LocalJSX.HvStatusbar & JSXBase.HTMLAttributes<HTMLHvStatusbarElement>;
    }
  }
}


