/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  LocationOption,
} from './components/viewer-component/viewer-options';
import {
  Overlay,
} from './overlay';

export namespace Components {
  interface HarmonizedPdf {}
  interface HarmonizedSpinner {}
  interface HarmonizedViewer {
    'annotationsShow': boolean;
    'enableToolbar': boolean;
    'enableTopbar': boolean;
    'language': string;
    'navigationHeight'?: number;
    'navigationLocation': LocationOption;
    'page': number;
    'parameterUrl': string;
    'totalPages': number;
  }
  interface HarmonizedViewerMessage {
    'class': string;
    'text': string;
    'type': string;
  }
  interface HarmonizedViewerOpenseadragon {
    'getOverlays': () => Promise<Overlay[]>;
  }
  interface HarmonizedViewerTopbar {}
  interface HarmonizedZoomSlider {}
  interface HvAnnotations {}
  interface HvNavigation {}
  interface HvSettings {}
  interface HvStatusbar {}
  interface HvToolbar {}
  interface HvViewport {}
}

declare global {


  interface HTMLHarmonizedPdfElement extends Components.HarmonizedPdf, HTMLStencilElement {}
  var HTMLHarmonizedPdfElement: {
    prototype: HTMLHarmonizedPdfElement;
    new (): HTMLHarmonizedPdfElement;
  };

  interface HTMLHarmonizedSpinnerElement extends Components.HarmonizedSpinner, HTMLStencilElement {}
  var HTMLHarmonizedSpinnerElement: {
    prototype: HTMLHarmonizedSpinnerElement;
    new (): HTMLHarmonizedSpinnerElement;
  };

  interface HTMLHarmonizedViewerElement extends Components.HarmonizedViewer, HTMLStencilElement {}
  var HTMLHarmonizedViewerElement: {
    prototype: HTMLHarmonizedViewerElement;
    new (): HTMLHarmonizedViewerElement;
  };

  interface HTMLHarmonizedViewerMessageElement extends Components.HarmonizedViewerMessage, HTMLStencilElement {}
  var HTMLHarmonizedViewerMessageElement: {
    prototype: HTMLHarmonizedViewerMessageElement;
    new (): HTMLHarmonizedViewerMessageElement;
  };

  interface HTMLHarmonizedViewerOpenseadragonElement extends Components.HarmonizedViewerOpenseadragon, HTMLStencilElement {}
  var HTMLHarmonizedViewerOpenseadragonElement: {
    prototype: HTMLHarmonizedViewerOpenseadragonElement;
    new (): HTMLHarmonizedViewerOpenseadragonElement;
  };

  interface HTMLHarmonizedViewerTopbarElement extends Components.HarmonizedViewerTopbar, HTMLStencilElement {}
  var HTMLHarmonizedViewerTopbarElement: {
    prototype: HTMLHarmonizedViewerTopbarElement;
    new (): HTMLHarmonizedViewerTopbarElement;
  };

  interface HTMLHarmonizedZoomSliderElement extends Components.HarmonizedZoomSlider, HTMLStencilElement {}
  var HTMLHarmonizedZoomSliderElement: {
    prototype: HTMLHarmonizedZoomSliderElement;
    new (): HTMLHarmonizedZoomSliderElement;
  };

  interface HTMLHvAnnotationsElement extends Components.HvAnnotations, HTMLStencilElement {}
  var HTMLHvAnnotationsElement: {
    prototype: HTMLHvAnnotationsElement;
    new (): HTMLHvAnnotationsElement;
  };

  interface HTMLHvNavigationElement extends Components.HvNavigation, HTMLStencilElement {}
  var HTMLHvNavigationElement: {
    prototype: HTMLHvNavigationElement;
    new (): HTMLHvNavigationElement;
  };

  interface HTMLHvSettingsElement extends Components.HvSettings, HTMLStencilElement {}
  var HTMLHvSettingsElement: {
    prototype: HTMLHvSettingsElement;
    new (): HTMLHvSettingsElement;
  };

  interface HTMLHvStatusbarElement extends Components.HvStatusbar, HTMLStencilElement {}
  var HTMLHvStatusbarElement: {
    prototype: HTMLHvStatusbarElement;
    new (): HTMLHvStatusbarElement;
  };

  interface HTMLHvToolbarElement extends Components.HvToolbar, HTMLStencilElement {}
  var HTMLHvToolbarElement: {
    prototype: HTMLHvToolbarElement;
    new (): HTMLHvToolbarElement;
  };

  interface HTMLHvViewportElement extends Components.HvViewport, HTMLStencilElement {}
  var HTMLHvViewportElement: {
    prototype: HTMLHvViewportElement;
    new (): HTMLHvViewportElement;
  };
  interface HTMLElementTagNameMap {
    'harmonized-pdf': HTMLHarmonizedPdfElement;
    'harmonized-spinner': HTMLHarmonizedSpinnerElement;
    'harmonized-viewer': HTMLHarmonizedViewerElement;
    'harmonized-viewer-message': HTMLHarmonizedViewerMessageElement;
    'harmonized-viewer-openseadragon': HTMLHarmonizedViewerOpenseadragonElement;
    'harmonized-viewer-topbar': HTMLHarmonizedViewerTopbarElement;
    'harmonized-zoom-slider': HTMLHarmonizedZoomSliderElement;
    'hv-annotations': HTMLHvAnnotationsElement;
    'hv-navigation': HTMLHvNavigationElement;
    'hv-settings': HTMLHvSettingsElement;
    'hv-statusbar': HTMLHvStatusbarElement;
    'hv-toolbar': HTMLHvToolbarElement;
    'hv-viewport': HTMLHvViewportElement;
  }
}

declare namespace LocalJSX {
  interface HarmonizedPdf {}
  interface HarmonizedSpinner {}
  interface HarmonizedViewer {
    'annotationsShow'?: boolean;
    'enableToolbar'?: boolean;
    'enableTopbar'?: boolean;
    'language'?: string;
    'navigationHeight'?: number;
    'navigationLocation'?: LocationOption;
    'onCanvasLoaded'?: (event: CustomEvent<any>) => void;
    'onGoto'?: (event: CustomEvent<any>) => void;
    'onManifestLoaded'?: (event: CustomEvent<any>) => void;
    'onNextLoad'?: (event: CustomEvent<any>) => void;
    'page'?: number;
    'parameterUrl'?: string;
    'totalPages'?: number;
  }
  interface HarmonizedViewerMessage {
    'class'?: string;
    'text'?: string;
    'type'?: string;
  }
  interface HarmonizedViewerOpenseadragon {
    'onOverlayClick'?: (event: CustomEvent<any>) => void;
  }
  interface HarmonizedViewerTopbar {}
  interface HarmonizedZoomSlider {}
  interface HvAnnotations {}
  interface HvNavigation {}
  interface HvSettings {}
  interface HvStatusbar {}
  interface HvToolbar {}
  interface HvViewport {}

  interface IntrinsicElements {
    'harmonized-pdf': HarmonizedPdf;
    'harmonized-spinner': HarmonizedSpinner;
    'harmonized-viewer': HarmonizedViewer;
    'harmonized-viewer-message': HarmonizedViewerMessage;
    'harmonized-viewer-openseadragon': HarmonizedViewerOpenseadragon;
    'harmonized-viewer-topbar': HarmonizedViewerTopbar;
    'harmonized-zoom-slider': HarmonizedZoomSlider;
    'hv-annotations': HvAnnotations;
    'hv-navigation': HvNavigation;
    'hv-settings': HvSettings;
    'hv-statusbar': HvStatusbar;
    'hv-toolbar': HvToolbar;
    'hv-viewport': HvViewport;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'harmonized-pdf': LocalJSX.HarmonizedPdf & JSXBase.HTMLAttributes<HTMLHarmonizedPdfElement>;
      'harmonized-spinner': LocalJSX.HarmonizedSpinner & JSXBase.HTMLAttributes<HTMLHarmonizedSpinnerElement>;
      'harmonized-viewer': LocalJSX.HarmonizedViewer & JSXBase.HTMLAttributes<HTMLHarmonizedViewerElement>;
      'harmonized-viewer-message': LocalJSX.HarmonizedViewerMessage & JSXBase.HTMLAttributes<HTMLHarmonizedViewerMessageElement>;
      'harmonized-viewer-openseadragon': LocalJSX.HarmonizedViewerOpenseadragon & JSXBase.HTMLAttributes<HTMLHarmonizedViewerOpenseadragonElement>;
      'harmonized-viewer-topbar': LocalJSX.HarmonizedViewerTopbar & JSXBase.HTMLAttributes<HTMLHarmonizedViewerTopbarElement>;
      'harmonized-zoom-slider': LocalJSX.HarmonizedZoomSlider & JSXBase.HTMLAttributes<HTMLHarmonizedZoomSliderElement>;
      'hv-annotations': LocalJSX.HvAnnotations & JSXBase.HTMLAttributes<HTMLHvAnnotationsElement>;
      'hv-navigation': LocalJSX.HvNavigation & JSXBase.HTMLAttributes<HTMLHvNavigationElement>;
      'hv-settings': LocalJSX.HvSettings & JSXBase.HTMLAttributes<HTMLHvSettingsElement>;
      'hv-statusbar': LocalJSX.HvStatusbar & JSXBase.HTMLAttributes<HTMLHvStatusbarElement>;
      'hv-toolbar': LocalJSX.HvToolbar & JSXBase.HTMLAttributes<HTMLHvToolbarElement>;
      'hv-viewport': LocalJSX.HvViewport & JSXBase.HTMLAttributes<HTMLHvViewportElement>;
    }
  }
}


